/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ivanda
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        
        initComponents();
            pemesanField.putClientProperty("JTextField.placeholderText", "Nama pemesan");
            nomorField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
            getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pemesanField = new javax.swing.JTextField();
        nomorField = new javax.swing.JTextField();
        kotaCombo = new javax.swing.JComboBox<>();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        bagasiCb = new javax.swing.JCheckBox();
        asuransiCb = new javax.swing.JCheckBox();
        makanCb = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        gelapToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama pemesan");

        jLabel2.setText("Nomor HP");

        jLabel3.setText("Kota tujuan");

        jLabel4.setText("Kelas");

        jLabel5.setText("Fasilitas tambahan");

        jLabel6.setText("Catatan");

        pemesanField.addActionListener(this::pemesanFieldActionPerformed);

        nomorField.addActionListener(this::nomorFieldActionPerformed);

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasgroup.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        kelasgroup.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");

        kelasgroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");

        bagasiCb.setText("Bagasi");

        asuransiCb.setText("Asuransi");

        makanCb.setText("Makan");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        gelapToggle.setText("Mode Gelap");
        gelapToggle.addActionListener(this::gelapToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bisnisRadio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(gelapToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesanButton))
                        .addComponent(makanCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asuransiCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ekonomiRadio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eksekutifRadio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bagasiCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pemesanField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomorField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kotaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekonomiRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bisnisRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eksekutifRadio))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagasiCb)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(makanCb)
                .addGap(18, 18, 18)
                .addComponent(asuransiCb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanButton)
                    .addComponent(gelapToggle))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemesanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesanFieldActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_pemesanFieldActionPerformed

    private void nomorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorFieldActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
tampilkanRingkasan();        // TODO add your handling code here:
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void gelapToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gelapToggleActionPerformed
    gantiTema(gelapToggle.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_gelapToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCb;
    private javax.swing.JCheckBox bagasiCb;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JToggleButton gelapToggle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasgroup;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JCheckBox makanCb;
    private javax.swing.JTextField nomorField;
    private javax.swing.JTextField pemesanField;
    private javax.swing.JButton pesanButton;
    // End of variables declaration//GEN-END:variables

    
private void tampilkanRingkasan() {
        String kelas = ekonomiRadio.isSelected() ? "Ekonomi" : bisnisRadio.isSelected() ? "Bisnis" : "Eksekutif";
        List<String> fasilitasTambahan = new ArrayList<>();
        for (JCheckBox cb : List.of(bagasiCb, makanCb, makanCb)) {
            if (cb.isSelected()) {
                fasilitasTambahan.add(cb.getText());
            }
        }
        String pesan = "Nama: " + pemesanField.getText()
                + "\nNomor: " + nomorField.getText()
                + "\nKota tujuan: " + kotaCombo.getSelectedItem()
                + "\nJenis Kelamin: " + kelas
                + "\nfasilitasTambahan: " + (fasilitasTambahan.isEmpty() ? "-" : String.join(", ", fasilitasTambahan))
                + "\ncatatan: " + catatanArea.getText()
                ;
        JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran",
                JOptionPane.INFORMATION_MESSAGE);
    }
    
private void gantiTema(boolean gelap) {
            if (gelap) {
                FlatDarkLaf.setup();
            } else {
                FlatLightLaf.setup();
            }
            FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
            gelapToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
}

}
